### ISSUE TITLE
upgrade to support dbt-core v1.6.0

### ISSUE THREAD

**Issue by dataders** [ClickHouse/dbt-clickhouse#164]
## Background 

Minor version `v1.6` is targeted for final release on July 27, 2023. As a maintainer of a dbt adapter, we strongly encourage you to release a corresponding minor version increment to ensure users of your adapter can make use of this new minor version.

## How to upgrade

https://github.com/dbt-labs/dbt-core/discussions/7958 is an open discussion with more detailed information. If you have questions, please put them there!

The above linked guide has more information, but below is a high-level checklist of work that would enable a successful 1.6.0 release of your adapter:

```[tasklist]
### Tasks
- [ ] SUPPORT: materialized views
- [ ] SUPPORT: new `clone` command
- [x] BEHIND THE SCENES: Drop support for Python 3.7 (if you haven't already)
- [x] BEHIND THE SCENES: new arg for `adapter.execute()`
- [ ] BEHIND THE SCENES: ensure support for revamped `dbt debug``
- [ ] BEHIND THE SCENES: Add support for new/modified relevant tests
```

## the next minor release: `1.7.0`

FYI, `dbt-core==1.7.0` is expected to be released on October 12, 2023 in time for [Coalesce](https://coalesce.getdbt.com/), the annual analytics engineering conference!

**Comment by zli06160** [comment]
Is there anyone working on the upgrade?

I had an issue few days ago, i would use `dbt-core>=1.4.8` under the constraint: 
-c https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.11.txt

So the upgrade is necessary. 
 c.c. @genzgd @gfunc

**Comment by dataders** [comment]
@zli06160 I think this might be related to https://github.com/dbt-labs/dbt-snowflake/issues/687#issuecomment-1631265068

**Comment by zli06160** [comment]
@dataders Thanks a lot for the investigation! It solved half of my problem.

Actually `dbt-clickhouse==1.4.8` worked perfectly with the constraint file https://raw.githubusercontent.com/apache/airflow/constraints-2.5.1/constraints-3.10.txt

But for https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.11.txt and `dbt-core>=1.6.0` there are still some works to do.

Of course, there is no more need to follow the constraint file line by line.

**Comment by genzgd** [comment]
Just a heads up for folks watching this issue -- the `dbt-core` implementation for materialized views is very PostgreSQL specific and is not compatible with ClickHouse Materialized views.  The initial 1.6.0 release of `dbt-clickhouse` will accordingly not include MV support.

In particular, a PostgreSQL (or Oracle) MV is static, containing the data from a SELECT query at the time the MV is created.  This static data can be "REFRESHed" with a SQL query.  ClickHouse MVs are equivalent to standard SQL "INSERT TRIGGERS", where data inserted in to the source table is transformed by the SQL query and immediately inserted into the target table.  This is much different behavior and not really consistent with the dbt execution model, which is generally batch oriented.
